<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Cart</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c70bd23b-4b9c-4919-bc5c-2a1caf0cffbb</testSuiteGuid>
   <testCaseLink>
      <guid>fd37ecf2-21db-4367-ad07-2bf3c4d0e639</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/Add To Cart</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5fe6f97-2702-4062-b6e2-558e43098c2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3707e5b7-3fd9-44ab-8705-82554a1141ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18da9a70-f48a-4daf-8b48-e3fb2d555469</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c01bbad1-229c-449a-9f22-f643010d90f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/Remove From Cart</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e13f6417-983d-478d-9875-354dd7ad2c01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3ce1cde-c069-4fd8-84f9-f8e68a688474</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>620ef47c-bc4a-411c-82ef-80f07a4c8c0e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1a736f3-7cf3-4515-9873-b7a4446bdd72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/Checkout</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a3c4d20d-9c9e-407a-aedc-8ffd1c34ad44</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Chckout/CheckoutData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd904977-de83-4ea4-9feb-4d149d07f5db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a52ef1c0-789e-4cfa-a87f-af8491d2be79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>668a8068-405f-4aa4-b774-ee8d353d405c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a3c4d20d-9c9e-407a-aedc-8ffd1c34ad44</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>firstName</value>
         <variableId>1ab3df72-8037-40e6-a2e7-eac7816a8919</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a3c4d20d-9c9e-407a-aedc-8ffd1c34ad44</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lastName</value>
         <variableId>c565bc9a-f00c-4770-9977-63c5a31d8f64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a3c4d20d-9c9e-407a-aedc-8ffd1c34ad44</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>postalCode</value>
         <variableId>0157120b-f458-4ab6-8078-1647c9382f99</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2e9829ae-1089-44d3-ae3d-f83566e2fda7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/Incorrect Checkout Missing Postal Code</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>92b89146-bf02-4d5a-8a68-0bc7568fa770</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Chckout/CheckoutData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7576b2d0-e8b3-4a97-b0af-c148ae9710e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15135e79-db36-4e1c-9de2-27cde31cef58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2f869ae-ef55-4ed9-a9f2-cdcd79d3d5db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>92b89146-bf02-4d5a-8a68-0bc7568fa770</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>firstName</value>
         <variableId>d9bc1b73-d68d-4df6-a02b-7bc5b5ae7853</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>92b89146-bf02-4d5a-8a68-0bc7568fa770</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lastName</value>
         <variableId>aa963ba6-2951-4544-afe0-d643d597841f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
