<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4a28d391-4154-4f73-95a7-76b23221b6ff</testSuiteGuid>
   <testCaseLink>
      <guid>6a15c636-1dd1-42d8-a821-a0a114502cb8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Correct Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e77148b5-b07d-46d4-a080-983dc0cf5717</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData/CorrectLoginData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ec84ccf-f984-4aa3-804f-371abe4fd381</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e77148b5-b07d-46d4-a080-983dc0cf5717</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>login</value>
         <variableId>79f7b22e-383d-4537-aaf2-affb21036690</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e77148b5-b07d-46d4-a080-983dc0cf5717</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>127d26e5-664c-4ec3-bcdf-43ae85ad6db4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cdce912a-8f11-47c8-a8c7-d42e2bc9849e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Incorrect Login Empty Credentials</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4dafe30-92de-4b64-99a0-b072e7e991f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebd627dc-8a1c-4b16-aeda-a0f49a7f0c3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd34c353-cf23-46ff-bd9a-ac257294f71c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9681028c-292d-4ae8-8320-96661c906dca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Incorrect Login Incorrect Credentials</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b7052789-9ee3-42f7-a8f9-2b0e9b44ba77</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData/IncorrectLoginData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a9ae086-d2ca-46a7-ab1b-3018b0b7686a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b7052789-9ee3-42f7-a8f9-2b0e9b44ba77</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>login</value>
         <variableId>801b711b-58b4-41c5-8d3b-533470728c0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b7052789-9ee3-42f7-a8f9-2b0e9b44ba77</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>c0169979-f0f7-4652-80ef-9988ccf6c88f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
