<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SuiteWithErrors</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>dd08c3f8-e052-4bf9-822c-0be2095ba9d9</testSuiteGuid>
   <testCaseLink>
      <guid>23819082-60e1-4378-9e71-6e7c9ce16c1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Special Errors/About Page Error</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d3a0655-42db-4adc-8aef-333885c89122</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da44b2f3-53d8-40ff-b860-123792e87308</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbc0b81f-bbc5-42d6-9060-7e8a8d0022f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3c305728-be4a-472a-bbb3-7b3af3aa9ca7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Special Errors/Image Load Error</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7223ca46-4a81-4f9d-a3c6-583e56fff59a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c78e5425-894d-42ed-a44b-42faa2c0a9ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1eb01e7d-d85b-4f50-a648-bcac735899e6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
